name: UrbanTrack CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      

      - name: Install Frontend dependencies
        working-directory: urbantrack-frontend
        run: npm install

      - name: Build Frontend
        working-directory: urbantrack-frontend
        run: npm run build
      
     
      - name: Install Backend dependencies
        working-directory: urbantrack-backend
        run: npm install

      - name: Test Backend
        working-directory: urbantrack-backend
        run: npm test || echo "Pas encore de tests"

      